baseURL = "https://resume.nathanwillson.com"
languageCode = "en-us"
title = "Nathan Willson - Resume"
author = "Nathan Willson"
enableRobotsTXT = true

[params]
	email = "contact@nathanwillson.com"
  github = "https://github.com/nbw/"
  github = "https://gitlab.com/nathanwillson"
  twitter_handle = "nathanwillson"
